### ISSUE TITLE
Feature Request: Series Genre Tags

### ISSUE THREAD

**Issue by bpepple** [bpepple/metron#117]
**Is your feature request related to a problem? Please describe.**
Might be nice to add genre tags to a series, since most metadata formats provide a genre element.

**Describe the solution you'd like**
Would require adding a genre field either using a m2m or using a Postgres ArrayField with multiple choices

**Additional context**
Need to collect from the community a list of possible genre types.

**Comment by bpepple** [comment]
Possible list of genres:

- Horror
- Fantasy
- Romance
- War
- Western
- Science Fiction
- Spy or Espionage 
- Super-Hero
- Humor
- Adult
- Erotic

**Comment by Dracon23** [comment]
* Space-Opera 
* Dystopian Fiction 
* High Fantasy 
* Modern Fantasy 
* Urban Fantasy 
* Cyberpunk 
* Steampunk

**Comment by bpepple** [comment]
> * Space-Opera
<snip>

Thanks for the suggestions, I'm thinking right now it make sense to **not** use sub-genres since that could lead to an overwhelming number of choices for contributors.
