### ISSUE TITLE
Sort credit roles alphabetically.

### ISSUE THREAD

**Issue by THElegend5** [bpepple/metron#143]
**Is your feature request related to a problem? Please describe.**
Currently in credits the roles are sorted in a random order which makes it pretty hard to find the role you are looking for.

**Describe the solution you'd like**
Sort the roles in an alphabetical order to make it easier to find the role you are looking for.

**Comment by bpepple** [comment]
Originally, I did sort the roles alphabetically but I found due to role naming discrepancies by the different publishers folks were not finding the correct roles when entering the data. So, my solution was to group _like_ roles together to increase invisibility.

Here's what I came up with:
```
>>> for i in roles:
...     print(i)
... 
Writer
Script
Story
Plot
Interviewer
Artist
Penciller
Breakdowns
Illustrator
Layouts
Inker
Embellisher
Finishes
Ink Assists
Colorist
Color Separations
Color Assists
Color Flats
Digital Art Technician
Gray Tone
Letterer
Cover
Editor
Consulting Editor
Assistant Editor
Associate Editor
Group Editor
Senior Editor
Managing Editor
Collection Editor
Production
Designer
Logo Design
Supervising Editor
Executive Editor
Editor In Chief
President
Publisher
Chief Creative Officer
```
Not 100% sure I'd want to switch back since I found the problem experienced before has largely disappeared.

**Comment by THElegend5** [comment]
> Originally, I did sort the roles alphabetically but I found due to role naming discrepancies by the different publishers folks were not finding the correct roles when entering the data. So, my solution was to group _like_ roles together to increase invisibility.

The current system would work pretty nicely if more roles were visible at a time, but without that it feels like you are just blindly going in and would require you to remember where mostly every type of role is present. I was gonna open request for being able to see more things at a time anyway as 4 at a time is way too little imo.

**Comment by bpepple** [comment]
Increasing the number is something easy to do, just don't want to make it so big it makes the form difficult to navigate. How many items do you thing we should show?

**Comment by bpepple** [comment]
I'm leaning toward increasing the rows to 5-8 (depending what looks best). Making it collapsible wouldn't really work imo, since collapsing something usually requires having a title/bar to collapse it into, which doesn't really fix the problem since it would be done for the whole credits section.

**Comment by THElegend5** [comment]
> I'm leaning toward increasing the rows to 5-8 (depending what looks best). Making it collapsible wouldn't really work imo, since collapsing something usually requires having a title/bar to collapse it into, which doesn't really fix the problem here since it would be done for the whole credits section.
> 
> In addition, I'm not really sure I want to resurrect a dead [project](https://github.com/creativebulma/bulma-collapsible) to implement it, but maybe I'll look into it a bit to see how much additional work it would create.

I was talking about only this section being collapsible as it is the solution every manga/comic database uses and it makes since you might want to see most of them at the same time but have it hidden when not being used.
![image](https://user-images.githubusercontent.com/63903377/195836548-be7a4129-8f66-47d8-a26f-91330f8034e7.png)

**Comment by bpepple** [comment]
> I was talking about only this section being collapsible as it is the solution every manga/comic database uses and it makes since you might want to see most of them at the same time but have it hidden when not being used.

The problem I see with attempting to do that is there is no bar/title to capture the user click action and have the widget collapse into.

**Comment by bpepple** [comment]
Here's what it would look like it if I changed the widget size to 6.

![Screenshot from 2022-10-14 15-10-22](https://user-images.githubusercontent.com/8381/195923233-f1309068-3b0f-408c-b960-bd5405baba32.png)

Not terrible, but 5 might be better. If I get some time this weekend I'll around play around with using the select2 widget but if I remember right there was performance issues with Redis (which is what the widget uses to query the database)

**Comment by THElegend5** [comment]
> Here's what it would look like it if I changed the widget size to 6.
> 
> ![Screenshot from 2022-10-14 15-10-22](https://user-images.githubusercontent.com/8381/195923233-f1309068-3b0f-408c-b960-bd5405baba32.png)
> 
> Not terrible, but 5 might be better. If I get some time this weekend I'll around play around with using the select2 widget but if I remember correctly there was performance issues with Redis (which is what the widget uses to query the database)

This looks pretty good imo, 5 might again turn too low.

**Comment by bpepple** [comment]
Ok, this is a pretty easy thing to modify. so let's change it to 6 and see how that works out. If it turns out that doesn't solve the problem, we can always revert the change.

**Comment by bpepple** [comment]
Closing this for now, if it turns out it needs to be tweaked that's easy enough to do.

**Comment by bpepple** [comment]
Closing this for now, if it turns out it needs to be tweaked that's easy enough to do.
