### ISSUE TITLE
Feature Request: Universe Entries & Issue Tags

### ISSUE THREAD

**Issue by themadman0980** [bpepple/metron#173]
**Is your feature request related to a problem? Please describe.**
There are many different universes within comics from Marvel, DC and other publishers. It would be extremely helpful to classify the universe within which an issue occurs for filtering and organisation purposes, and to help with finding similar reading content.

**Describe the solution you'd like**
A new tag for issues titled "Universe", with a validated list of possible inputs from a centralised list of universes, each with a page describing the universe and its history. The process to add a universe to an issue would include creating a new Universe entry, and then going to an issue and selecting that Universe from the available list (as this grows, a search tool might be necessary). 

For example, Marvel has an extensive list of universes, however it makes sense to start with the common ones like Earth-616, the Ultimate Marvel universe, and the Star-Wars universe.

**Additional context**
As discussed on Matrix. 

This could be an optional field, so while it may be more effort to include, it's not necessary to include it for each issue unless somebody wants to go to the effort of updating this metadata.

Each universe would probably need to be linked to one or more publishers, and one or more issues. It seems more logical to link at an issue level rather than a series level, although it would be nice to be able to bulk update this tag for a whole series within the Metron db. It might be wise to allow an issue to be a part of more than 1 universe (if there's some transition mid-issue).

**Comment by bpepple** [comment]
Done some initial work on this the last day or so. I've created a `Universe` model that contains the following fields:

- **Publisher** _(Required)_: The publisher the universe is associated with. For now this is linked to just **one** publisher, off the top of my head I can't think of any universes that span multiple publishers. So, if folks have some examples please add a comment.
- **Name** _(Required)_: The name of the Universe. For ex. "Kingdom Come" or if it's doesn't have one it should be the designated name.
- **Designation**: The Designation for the universe. For ex. "Earth 22"
- **Description**: A description of the universe.
- **Image**: An image use to show the universe.
- **Attribution**: If the description uses text from another source (like Wikipedia) add a link to it.

And I've added a m2m `universes` field to the following models:

- Character
- Team
- Issue

It might be worth adding a m2m field to the `Series` model, but I'm not sure how worthwhile that would be, so if someone in the community has opinion add a comment.

Regarding bulk updating, I'm creating a management command to handle updating a series for a universe. For requests, I'm thinking of adding a Discussion Page Topic, where folks can add a _series_ & _universe_ info that needs to updated by the admin.

Here's a screenshot of what a Universe Detail page would look like:
![image](https://github.com/bpepple/metron/assets/8381/0c3a3845-d28d-4a59-b2df-7cfbfb1f4d45)

I've still go to add tests and update the API for the changes, but the bulk of the work is done.

@themadman0980: Are there any other aspects of this I need to address?

**Comment by themadman0980** [comment]
This sounds amazing! 

One of the main benefits of universe tags for me is as a filtering mechanism for searches, and as such it would be helpful for series to have access to this. Is it possible to make it a calculated read only field which pulls from all the associated issues in the series?

**Comment by bpepple** [comment]
> One of the main benefits of universe tags for me is as a filtering mechanism for searches, and as such it would be helpful for series to have access to this. Is it possible to make it a calculated read only field which pulls from all the associated issues in the series? 

What are you filtering for? Issues? Series?

**Comment by themadman0980** [comment]
At present, my main use case would be at a series level. But the data definitely belongs at an issue level given the potential for one off crossovers to a different universe IMO.
