### ISSUE TITLE
Account creation still not possible

### ISSUE THREAD

**Issue by 5h4k3** [bpepple/metron#194]
Few Month ago, I tried to sign-up with: Outlook (1), Gmail (3), Proton (2) and Yahoo (1) but unfortunately none worked.
So I waited a bit, then tried again today… Same. I can't create a account. 

1. Go to " https://metron.cloud/accounts/signup/ "
2. Click on " Sign up "
3. Enter information and the captcha
4. See error: " Invalid email address "

Tried with:
 - Windows 22H2 19045.3803
 - Firefox 121.0 64-bit
 - Edge 120.0.2210.91 64-bit
 
Or maybe I didn't understand that it's only compatible with Matrix, in which case it might be good to clarify instead of demanding a "valid" email…

In any case, I wish you a happy end of the year !
Cheers !

**Comment by bpepple** [comment]
What email domain are you using? Without knowing that I'm not sure how I can help. I know the user registration code is working since a few folks have signed up for accounts in the last 12 hours or so.

**Comment by 5h4k3** [comment]
Ha ! Sorry, I didn't know that the "Invalid email address" problem could come from something other than the provider...

Did you do something? Because I just tried again with "protonmail.com" it worked so I immediately gave up and finalized the registration with "gmail.com" (preferred address).

If not, do you have any idea what happened ? Mainly to understand where the problem could come from and going to my bed being less stupid… Right now it just seems weird to me.

Because about 6 or 8 months ago, it didn't work like it did earlier today. And there, it just happened without a problem.

However, to answer your question, I tried several times with several "hotmail.fr" (Outlook), "gmail.com", "protonmail.com", "proton.me" and "yahoo.fr"…

And the addresses that seem to work tonight were "protonmail.com" and "gmail.com".

Thanks for your time & your work.

**Comment by bpepple** [comment]
Not sure why you weren't able to add an account since other folks were able from the same services, regardless I've done a little reworking of the account creation code to weed out the spam & disposable email accounts and since you were able to *finally* add an account I'll go ahead and close this. Thx!
