### ISSUE TITLE
Query Issues by Rating

### ISSUE THREAD

**Issue by ComputerWolf** [bpepple/metron#247]
**Describe the solution you'd like**
The ability to query the API by the age rating

**Describe alternatives you've considered**
Retrieving a list of issues, fetching the issue data for each and checking the Rating field. However, this requires many unneeded requests.

**Comment by bpepple** [comment]
Ok, I'm about to merge the PR for this feature.

I'm using iexact for the lookup expression to prevent queries for `teen` from including `teen` _&_ `teen plus` in the queryset.

The available rating options (case insensitive) are as follows:

- Unknown
- Everyone
- Teen
- Mature
- Teen Plus
- CCA

This should be pushed to production in the next hour or so, and if you have any questions don't hesitate to ask.
