### ISSUE TITLE
Email address with + sign is rejected as invalid

### ISSUE THREAD

**Issue by PeteS4** [bpepple/metron#249]
**Describe the bug**
I tried registering with my perfectly valid email address that contains a plus sign (something like abc+def@example.org). The address is rejected as invalid.

**To Reproduce**
1. Go to https://metron.cloud/accounts/signup/
2. Enter data including an email address with a + sign
3. Click 'Sign up'

**Comment by bpepple** [comment]
Glanced at the logs with our e-mail verification service, and the only failure I see gave this response:

```
{
  "valid": false,
  "block": true,
  "disposable": false,
  "domain": "posteo.net",
  "text": "Invalid e-mail",
  "reason": "E-mail format is invalid",
  "risk": 10,
  "mx_host": null,
  "possible_typo": null,
  "mx_ip": null,
  "mx_info": null,
  "last_changed_at": "2024-05-26T16:08:39+00:00"
}
```
I know other accounts have a `+` in the email address in the past, but maybe our service no longer allows them. You might try removing the `+` filter hack and see if the works.

**Comment by PeteS4** [comment]
Yes, I removed the filter part and it worked fine .. I guess it's just a pet peeve of mine that an increasing number of web pages have this unnecessary hurdle 😌
