### ISSUE TITLE
Fetch data from CV itself when creating entry

### ISSUE THREAD

**Issue by rad96** [bpepple/metron#290]
Allow user to enter they CV API key as part of personal profile
Fetch CV issue/series/whatever endpoint with user-provided API key on client-side.
Fill some fields of creation form with data got from CV

Will be handy for filling info of series from ancient times

Libgen have done this in example, I expect something simillar:
![изображение](https://github.com/user-attachments/assets/687a3a7c-88d0-481d-8fad-57b9556bdc0f)

**Comment by bpepple** [comment]
Appreciate you thinking outside the box, but implementing a feature like this could potentially open the project to legal trouble since that would explicitly be against Comic Vine's [Terms of Use](https://comicvine.gamespot.com/api/).

**Comment by rad96** [comment]
Yeah, better to scrap it "in secret"
I see
