### ISSUE TITLE
Fuzzy/Wildcard Search

### ISSUE THREAD

**Issue by Buried-In-Code** [bpepple/metron#65]
**Is your feature request related to a problem? Please describe.**
The Website and API produce different search results.
If you search `/api/series?name=Spider-Man` you'll get 2 results but search `Spider-Man` via the Website and you get 51 Series.

**Describe the solution you'd like**
Option to make it fuzzy search by passing in a param or adding a wild card.
If there is a wildcard search it's not documented in the Schema

**Describe alternatives you've considered**
I've tried `*` and `%` wildcards neither work.

**Additional context**

**Comment by bpepple** [comment]
Django Rest Framework doesn't use wildcards, but to fix this I just need to create a Series filter (like the Issues filter) that uses `icontains` instead of the default lookup expression which is `exact`.  Most likely need to do the same thing for the other resources (ie. Arcs, Characters, etc.)

**Comment by bpepple** [comment]
Thanks for the bug report!
